### ISSUE TITLE
add additional players

### ISSUE THREAD

**Issue by two-dogs** [Koutch/Cinnamon-sound-with-apps-volume#7]
hello, how about a method to add additional players? 
i was thinking Kmplayer would look pretty smart on the players list, and i use it :)
another thing, i am 100% kde apps on cinn, i prefer the WM to Kwin

**Comment by Koutch** [comment]
hello
I essentially worked on volume per applications and the sliders to allow 150% volume, the rest comes from the original sound applet. and I don't used the player part of the applet (that's why I added an option to hide them ^^)
so I'm not sure but you can try to add 'Kmlayer' to the lists 'compatible_players' and 'support_seek' at lines 377 and 384 in applet.js

**Comment by Koutch** [comment]
is Kmplayer working with the applet now ? :)

**Comment by two-dogs** [comment]
On Saturday, March 14, 2015 18:10:33 Koutch wrote:
> is Kmplayer working with the applet now ? :)
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Koutch/Cinnamon-sound-with-apps-volume/issues/7#issuecomm
> ent-80788762
yes, it will show on playlist, but cant be controlled from applet, kodi (ex 
xbmc) same issue, although i am on System:    Host: linux-gumo Kernel: 
4.0.0-rc3-2.gd5c547f-desktop x86_64 (64 bit gcc: 4.8.3)
           Desktop: Cinnamon 2.4.3 (Gtk 3.14.9) dm: kdm Distro: openSUSE 
20150312 (Tumbleweed) so it may just be a opensuse issue

**Comment by somini** [comment]
That thing to control the player is a MPRIS interface, you better as around the kmplayer dev team.

**Comment by two-dogs** [comment]
On Saturday, March 14, 2015 19:07:22 somini 
wrote:
> MPRIS
i have mpris on kde via veromix, i dont see a mpris 
method via cinnamon, or a package for stand alone 
mpris from repos on opensuse, there may be issues 
related to opensuse one does not see on 
ubuntu/mint, but then i would not know, i have ran 
cinn from opensuse only

**Comment by somini** [comment]
I think the player itself has to provide some kind of interface, but that's with the kmplayer guys.
